/* AUTO-GENERATED by scripts/generate-routes.mjs — do not edit */
import WpMirrorPage, { buildMetadata } from "@/components/mirror/WpMirrorPage";
import content from "@/data/wordpress/content/post-content-strategy-for-seo.json";

export const metadata = buildMetadata(content);

export default function Page() {
  return <WpMirrorPage content={content} />;
}
