(function(){"use strict";var root=document.querySelector(".dgs-v1215");if(!root||root.dataset.dgsV1215Booted==="1")return;root.dataset.dgsV1215Booted="1";var raf=window.requestAnimationFrame||function(cb){return setTimeout(cb,16)};var idle=window.requestIdleCallback||function(cb){return setTimeout(cb,350)};var reducedMotion=window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches;var coarsePointer=window.matchMedia&&window.matchMedia("(pointer: coarse)").matches;var desktopMotion=window.matchMedia&&window.matchMedia("(min-width: 901px)").matches;var canUseWebGL=!reducedMotion&&desktopMotion&&!coarsePointer;function revealContent(){var items=Array.prototype.slice.call(root.querySelectorAll(".dgs-v1215-reveal"));if(!items.length)return;root.classList.add("motion-ready");function show(item){item.classList.add("is-visible")}
items.forEach(function(item,index){if(index<2||item.closest(".dgs-v1215-hero"))show(item);});if(reducedMotion||!("IntersectionObserver" in window)){items.forEach(show);return}
var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){show(entry.target);observer.unobserve(entry.target)}})},{threshold:0.06,rootMargin:"0px 0px -4% 0px"});items.forEach(function(item){if(!item.classList.contains("is-visible"))observer.observe(item);});setTimeout(function(){items.forEach(show)},1200)}
function updateScrollVars(){var ticking=!1;function update(){var rect=root.getBoundingClientRect();var start=window.pageYOffset+rect.top;var total=Math.max(root.offsetHeight-window.innerHeight,1);var current=window.pageYOffset-start;var progress=Math.min(Math.max(current/total,0),1);root.style.setProperty("--v1215-scroll",progress.toFixed(4));ticking=!1}
function requestUpdate(){if(!ticking){ticking=!0;raf(update)}}
update();window.addEventListener("scroll",requestUpdate,{passive:!0});window.addEventListener("resize",requestUpdate,{passive:!0})}
function initPointerMotion(){if(reducedMotion)return;var wrap=document.getElementById("dgs-v1215-robot-wrap");var img=document.getElementById("dgs-v1215-robot");var active=!1;var nx=0;var ny=0;var targetX=0;var targetY=0;function render(){active=!1;nx+=(targetX-nx)*0.12;ny+=(targetY-ny)*0.12;root.style.setProperty("--v1215-bg-x",(nx*-18).toFixed(2)+"px");root.style.setProperty("--v1215-bg-y",(ny*-14).toFixed(2)+"px");root.style.setProperty("--v1215-grid-x",(nx*10).toFixed(2)+"px");root.style.setProperty("--v1215-grid-y",(ny*8).toFixed(2)+"px");if(wrap&&img&&window.innerWidth>=900){wrap.style.transform="perspective(1300px) rotateY("+(nx*4).toFixed(2)+"deg) rotateX("+(-ny*3).toFixed(2)+"deg) translate3d("+(nx*8).toFixed(2)+"px,"+(ny*6).toFixed(2)+"px,0)";img.style.transform="scale(1.02) translate3d("+(nx*-7).toFixed(2)+"px,"+(ny*-5).toFixed(2)+"px,0)"}}
function requestRender(){if(!active){active=!0;raf(render)}}
window.addEventListener("pointermove",function(event){if(event.pointerType&&event.pointerType!=="mouse")return;targetX=(event.clientX/Math.max(window.innerWidth,1)-0.5)*2;targetY=(event.clientY/Math.max(window.innerHeight,1)-0.5)*2;requestRender()},{passive:!0});window.addEventListener("pointerleave",function(){targetX=0;targetY=0;if(wrap)wrap.style.transform="";if(img)img.style.transform="";requestRender()},{passive:!0})}
function loadScript(src){return new Promise(function(resolve,reject){var existing=document.querySelector('script[src="'+src+'"]');if(existing){if(window.THREE&&src.indexOf("three")!==-1){resolve();return}
existing.addEventListener("load",resolve,{once:!0});existing.addEventListener("error",reject,{once:!0});return}
var script=document.createElement("script");script.src=src;script.async=!0;script.defer=!0;script.onload=resolve;script.onerror=reject;document.head.appendChild(script)})}
function initThree(){if(root.dataset.dgsV1215Three==="1"||!canUseWebGL||!window.THREE)return;root.dataset.dgsV1215Three="1";var canvas=document.getElementById("dgs-v1215-canvas");if(!canvas)return;var THREE=window.THREE;root.classList.add("v1215-webgl-ready");var renderer=new THREE.WebGLRenderer({canvas:canvas,alpha:!0,antialias:!1,powerPreference:"high-performance"});var width=window.innerWidth;var height=window.innerHeight;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.25));renderer.setSize(width,height,!1);var scene=new THREE.Scene();var camera=new THREE.PerspectiveCamera(58,width/height,0.1,100);camera.position.set(0,0,8.5);function createCircleTexture(){var size=64;var canvasTex=document.createElement("canvas");canvasTex.width=size;canvasTex.height=size;var ctx=canvasTex.getContext("2d");var gradient=ctx.createRadialGradient(size/2,size/2,0,size/2,size/2,size/2);gradient.addColorStop(0,"rgba(255,255,255,1)");gradient.addColorStop(0.36,"rgba(255,255,255,.82)");gradient.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=gradient;ctx.beginPath();ctx.arc(size/2,size/2,size/2,0,Math.PI*2);ctx.fill();return new THREE.CanvasTexture(canvasTex)}
var particleTexture=createCircleTexture();var particleCount=width>1400?560:380;var positions=new Float32Array(particleCount*3);var colors=new Float32Array(particleCount*3);var palette=[new THREE.Color(0x00d4ff),new THREE.Color(0xfd5c62),new THREE.Color(0x9d4edd),new THREE.Color(0xffffff)];for(var i=0;i<particleCount;i++){var t=i/particleCount;var angle=t*Math.PI*8+Math.random();var radius=1.2+Math.random()*6;positions[i*3]=Math.cos(angle)*radius+(Math.random()-.5);positions[i*3+1]=Math.sin(angle)*radius*.45+(Math.random()-.5)*3.2;positions[i*3+2]=(Math.random()-.5)*9;var c=palette[Math.floor(Math.random()*palette.length)];colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b}
var geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.BufferAttribute(positions,3));geometry.setAttribute("color",new THREE.BufferAttribute(colors,3));var material=new THREE.PointsMaterial({size:.074,map:particleTexture,alphaMap:particleTexture,vertexColors:!0,transparent:!0,opacity:.86,depthWrite:!1,blending:THREE.AdditiveBlending});var points=new THREE.Points(geometry,material);scene.add(points);var running=!1;var clock=new THREE.Clock();function animate(){var time=clock.getElapsedTime();points.rotation.y=time*.022;points.rotation.x=Math.sin(time*.22)*.035;renderer.render(scene,camera)}
function start(){if(!running){running=!0;renderer.setAnimationLoop(animate)}}
function stop(){if(running){running=!1;renderer.setAnimationLoop(null)}}
function resize(){width=window.innerWidth;height=window.innerHeight;if(width<901){stop();canvas.style.display="none";return}
canvas.style.display="block";camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.25));renderer.setSize(width,height,!1);start()}
window.addEventListener("resize",resize,{passive:!0});resize()}
function bootMotion(){revealContent();updateScrollVars();initPointerMotion();if(canUseWebGL){idle(function(){if(window.THREE){initThree();return}
loadScript("https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js").then(initThree).catch(function(){root.classList.remove("v1215-webgl-ready")})})}}
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",bootMotion,{once:!0})}else{bootMotion()}})()