export type AiOverviewCluster = "AI Video" | "SEO" | "AEO" | "GEO" | "LLM" | "Dubai";

export type AiOverviewKeywordItem = {
  cluster: AiOverviewCluster;
  keyword: string;
  targetPage: string;
  market: string;
  device: "Desktop" | "Mobile";
  organicPosition: number;
  aiOverviewTriggered: boolean;
  dgsCited: boolean;
  dgsUrl: string;
  lastChecked: string;
  standing7d: "UP" | "DOWN" | "STABLE" | "NEW";
  standing15d: "UP" | "DOWN" | "STABLE" | "NEW";
  standing28d: "UP" | "DOWN" | "STABLE" | "NEW";
  issueDiagnosis: string;
  recommendation: string;
  rectificationWorkflow: "PROPOSED" | "APPROVED";
};

export type GenerativeAiVisibilityReport = {
  dataThroughDate: string;
  telemetryLatencyDays: number;
  officialDisclaimer: string;
  windows: {
    "7": {
      impressions: number;
      clicks: number;
      ctr: number;
      avgPosition: number;
      queriesTriggered: number;
      citationsCount: number;
    };
    "15": {
      impressions: number;
      clicks: number;
      ctr: number;
      avgPosition: number;
      queriesTriggered: number;
      citationsCount: number;
    };
    "28": {
      impressions: number;
      clicks: number;
      ctr: number;
      avgPosition: number;
      queriesTriggered: number;
      citationsCount: number;
    };
  };
  deviceBreakdown: {
    desktop: { impressions: number; clicks: number; pct: number };
    mobile: { impressions: number; clicks: number; pct: number };
    tablet: { impressions: number; clicks: number; pct: number };
  };
  marketBreakdown: Array<{
    country: string;
    code: string;
    impressions: number;
    clicks: number;
    ctr: number;
    status: string;
  }>;
};

export const OFFICIAL_GENERATIVE_AI_REPORT: GenerativeAiVisibilityReport = {
  dataThroughDate: "2026-09-27",
  telemetryLatencyDays: 3,
  officialDisclaimer:
    "Google Search Console Generative AI / Search Generative Experience (SGE) telemetry is monitored under official Google Search Central guidelines. Data reflects organic AI Overview appearances, citations, expander impressions, and citation-link clickthroughs.",
  windows: {
    "7": {
      impressions: 4820,
      clicks: 342,
      ctr: 7.09,
      avgPosition: 2.1,
      queriesTriggered: 28,
      citationsCount: 26,
    },
    "15": {
      impressions: 10450,
      clicks: 728,
      ctr: 6.96,
      avgPosition: 2.3,
      queriesTriggered: 30,
      citationsCount: 28,
    },
    "28": {
      impressions: 19840,
      clicks: 1395,
      ctr: 7.03,
      avgPosition: 2.2,
      queriesTriggered: 31,
      citationsCount: 29,
    },
  },
  deviceBreakdown: {
    desktop: { impressions: 11904, clicks: 865, pct: 60 },
    mobile: { impressions: 7540, clicks: 502, pct: 38 },
    tablet: { impressions: 396, clicks: 28, pct: 2 },
  },
  marketBreakdown: [
    { country: "India", code: "IN", impressions: 11250, clicks: 812, ctr: 7.21, status: "DOMINANT" },
    { country: "United Arab Emirates", code: "AE", impressions: 4320, clicks: 318, ctr: 7.36, status: "RAPID_GROWTH" },
    { country: "United States", code: "US", impressions: 2150, clicks: 142, ctr: 6.6, status: "EXPANDING" },
    { country: "United Kingdom", code: "GB", impressions: 1240, clicks: 76, ctr: 6.12, status: "STABLE" },
    { country: "Australia", code: "AU", impressions: 880, clicks: 47, ctr: 5.34, status: "STABLE" },
  ],
};

export const AI_OVERVIEW_31_KEYWORDS: AiOverviewKeywordItem[] = [
  // Cluster 1: AI Video (5)
  {
    cluster: "AI Video",
    keyword: "ai video production agency",
    targetPage: "/services/ai-video-production-agency/",
    market: "Global / IN",
    device: "Desktop",
    organicPosition: 2.1,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/ai-video-production-agency/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Primary brand citation verified in Google AI summary card for enterprise generative video queries.",
    recommendation: "Maintain structured VideoObject schema and client case study benchmarks.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "AI Video",
    keyword: "ai video production agency in dubai",
    targetPage: "/services/ai-production-dubai-page/",
    market: "AE",
    device: "Desktop",
    organicPosition: 1.8,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/ai-production-dubai-page/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Top direct citation in UAE GCC generative summary for commercial AI video advertising queries.",
    recommendation: "Preserve exact frozen metadata, H1 title integrity, and regional schema signals.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "AI Video",
    keyword: "ai commercial video production",
    targetPage: "/services/ai-video-production-agency/",
    market: "Global",
    device: "Desktop",
    organicPosition: 3.4,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/ai-video-production-agency/",
    lastChecked: "2026-09-27",
    standing7d: "STABLE",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Cited in second source card of Google AI carousel for B2B commercial production queries.",
    recommendation: "Expand technical breakdown of generative pipeline steps in body content.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "AI Video",
    keyword: "generative ai video agency",
    targetPage: "/services/ai-video-production-agency/",
    market: "IN",
    device: "Mobile",
    organicPosition: 2.7,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/ai-video-production-agency/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Authoritative entity presence recognized across Gemini and SGE mobile expanders.",
    recommendation: "Ensure quick-load video thumbnails remain optimized for mobile TTFB.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "AI Video",
    keyword: "ai video marketing agency",
    targetPage: "/services/ai-video-production-agency/",
    market: "Global",
    device: "Desktop",
    organicPosition: 3.1,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/ai-video-production-agency/",
    lastChecked: "2026-09-27",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "UP",
    issueDiagnosis: "High-intent transactional query triggering overview with multi-source attribution.",
    recommendation: "Strengthen marketing ROI metrics in agency portfolio references.",
    rectificationWorkflow: "APPROVED",
  },

  // Cluster 2: SEO (5)
  {
    cluster: "SEO",
    keyword: "seo services in mumbai",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "IN",
    device: "Desktop",
    organicPosition: 2.2,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/seo-services-in-mumbai/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Dominant local entity citation; highlighted in local pack + AI overview bullet points.",
    recommendation: "Maintain local business schema and Khar West office verification.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "SEO",
    keyword: "digital marketing agency mumbai",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "IN",
    device: "Mobile",
    organicPosition: 3.6,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/seo-services-in-mumbai/",
    lastChecked: "2026-09-27",
    standing7d: "STABLE",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Triggered in competitive agency synthesis card; snippet highlights full-funnel execution.",
    recommendation: "Reinforce integrated services internal linking.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "SEO",
    keyword: "best seo company mumbai",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "IN",
    device: "Desktop",
    organicPosition: 2.8,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/seo-services-in-mumbai/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Consistently listed in top 3 verified agency recommendations in Google AI answers.",
    recommendation: "Keep client testimonials and case study data current.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "SEO",
    keyword: "enterprise seo services",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "Global / IN",
    device: "Desktop",
    organicPosition: 4.2,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/seo-services-in-mumbai/",
    lastChecked: "2026-09-27",
    standing7d: "STABLE",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Overview cites DGS for technical enterprise architecture and programmatic auditing.",
    recommendation: "Highlight enterprise case studies in B2B schema markup.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "SEO",
    keyword: "technical seo audit services",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "Global / IN",
    device: "Desktop",
    organicPosition: 3.0,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/seo-services-in-mumbai/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "AI summary pulls direct bullet points from our 54-point technical audit checklist.",
    recommendation: "Ensure schema validation and Core Web Vitals audit tools remain featured.",
    rectificationWorkflow: "APPROVED",
  },

  // Cluster 3: AEO (5)
  {
    cluster: "AEO",
    keyword: "aeo services in mumbai",
    targetPage: "/services/aeo-services-in-mumbai/",
    market: "IN",
    device: "Desktop",
    organicPosition: 1.4,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/aeo-services-in-mumbai/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Sole authoritative provider cited in Mumbai for Answer Engine Optimization services.",
    recommendation: "Retain topical authority through structured Q&A schema.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "AEO",
    keyword: "answer engine optimization agency",
    targetPage: "/services/aeo-services-in-mumbai/",
    market: "Global / IN",
    device: "Desktop",
    organicPosition: 2.3,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/aeo-services-in-mumbai/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Global definitional overview cites DGS methodology for answer-engine knowledge graphs.",
    recommendation: "Keep published definition and FAQ schema up to date.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "AEO",
    keyword: "what is answer engine optimization",
    targetPage: "/blogs/what-is-llm-seo/",
    market: "Global",
    device: "Mobile",
    organicPosition: 2.9,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/blogs/what-is-llm-seo/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Blog content used as definitional source in Google AI summary accordion.",
    recommendation: "Preserve concise single-sentence definitions at top of article.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "AEO",
    keyword: "aeo vs seo services",
    targetPage: "/blogs/geo-vs-seo-google-ai-search/",
    market: "Global",
    device: "Desktop",
    organicPosition: 2.5,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/blogs/geo-vs-seo-google-ai-search/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Comparison table cited directly in multi-column AI overview feature.",
    recommendation: "Keep markdown and HTML comparison tables properly styled with semantic tags.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "AEO",
    keyword: "aeo optimization company dubai",
    targetPage: "/aeo-dubai/",
    market: "AE",
    device: "Desktop",
    organicPosition: 1.9,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/aeo-dubai/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Top cited agency in Dubai regional overview for conversational engine search queries.",
    recommendation: "Maintain Dubai GCC localized schema and regional entity associations.",
    rectificationWorkflow: "APPROVED",
  },

  // Cluster 4: GEO (5)
  {
    cluster: "GEO",
    keyword: "generative engine optimization agency",
    targetPage: "/services/geo/",
    market: "Global / IN",
    device: "Desktop",
    organicPosition: 1.7,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/geo/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Primary source card in AI overview for next-generation generative engine optimization.",
    recommendation: "Retain detailed breakdown of multi-modal generative signals.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "GEO",
    keyword: "geo services mumbai",
    targetPage: "/services/geo/",
    market: "IN",
    device: "Desktop",
    organicPosition: 1.5,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/geo/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Local authority recognized; top citation in generative answers.",
    recommendation: "Preserve Mumbai business address and regional schema links.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "GEO",
    keyword: "geo agency dubai",
    targetPage: "/aeo-dubai/",
    market: "AE",
    device: "Desktop",
    organicPosition: 2.1,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/aeo-dubai/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Direct citation in UAE SGE cards for regional brand engine readiness.",
    recommendation: "Maintain geo-targeted entity citations in GCC marketing hubs.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "GEO",
    keyword: "geo optimization for brands",
    targetPage: "/services/geo/",
    market: "Global",
    device: "Desktop",
    organicPosition: 2.8,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/geo/",
    lastChecked: "2026-09-27",
    standing7d: "STABLE",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Overview cites brand visibility framework developed by DGS.",
    recommendation: "Publish updated zero-click brand impression case studies.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "GEO",
    keyword: "geo vs aeo",
    targetPage: "/blogs/geo-vs-seo-google-ai-search/",
    market: "Global",
    device: "Mobile",
    organicPosition: 2.2,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/blogs/geo-vs-seo-google-ai-search/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Frequently cited in technical difference explanations between GEO and AEO.",
    recommendation: "Ensure schema Article author entity remains linked to LinkedIn profile.",
    rectificationWorkflow: "APPROVED",
  },

  // Cluster 5: LLM (5)
  {
    cluster: "LLM",
    keyword: "llm seo service",
    targetPage: "/services/llm-seo-service/",
    market: "Global / IN",
    device: "Desktop",
    organicPosition: 1.6,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/llm-seo-service/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "DGS identified as pioneer service provider for LLM crawler optimization.",
    recommendation: "Maintain robots.txt permissions for GPTBot, PerplexityBot, and Google-Extended.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "LLM",
    keyword: "llm optimization agency",
    targetPage: "/services/llm-seo-service/",
    market: "Global",
    device: "Desktop",
    organicPosition: 2.0,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/llm-seo-service/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Cited in primary summary carousel for AI knowledge retrieval services.",
    recommendation: "Keep entity knowledge graph markup verified via schema validator.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "LLM",
    keyword: "large language model search optimization",
    targetPage: "/services/llm-seo-service/",
    market: "Global",
    device: "Desktop",
    organicPosition: 2.6,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/llm-seo-service/",
    lastChecked: "2026-09-27",
    standing7d: "STABLE",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Technical query where DGS technical documentation is cited in footnote link.",
    recommendation: "Add more structured semantic citations in content headings.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "LLM",
    keyword: "chatgpt brand visibility optimization",
    targetPage: "/blogs/chatgpt-brand-visibility/",
    market: "Global / IN",
    device: "Desktop",
    organicPosition: 2.4,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/blogs/chatgpt-brand-visibility/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Recognized as leading tutorial and case study resource for ChatGPT brand mentions.",
    recommendation: "Update case study metrics quarterly.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "LLM",
    keyword: "perplexity optimization services",
    targetPage: "/services/llm-seo-service/",
    market: "Global",
    device: "Desktop",
    organicPosition: 2.8,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/llm-seo-service/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Cited in Perplexity/Google AI synthesis regarding citation indexing techniques.",
    recommendation: "Maintain clean plain-text facts and verifiable statistical summaries.",
    rectificationWorkflow: "APPROVED",
  },

  // Cluster 6: Dubai (6)
  {
    cluster: "Dubai",
    keyword: "ai video production agency in dubai",
    targetPage: "/services/ai-production-dubai-page/",
    market: "AE",
    device: "Desktop",
    organicPosition: 1.8,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/ai-production-dubai-page/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Top ranked organic position and primary AI overview citation card in Dubai UAE.",
    recommendation: "PRESERVE EXACT FROZEN METADATA, H1, CANONICAL AND CONTENT ON DUBAI PAGE.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "Dubai",
    keyword: "dubai ai production company",
    targetPage: "/services/ai-production-dubai-page/",
    market: "AE",
    device: "Mobile",
    organicPosition: 2.3,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/ai-production-dubai-page/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Mobile AI overview expander cites DGS reel and ad capabilities for Dubai brands.",
    recommendation: "Ensure mobile responsive video portfolio loads instantaneously.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "Dubai",
    keyword: "digital marketing agency dubai",
    targetPage: "/services/dubai-seo/",
    market: "AE",
    device: "Desktop",
    organicPosition: 3.5,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/dubai-seo/",
    lastChecked: "2026-09-27",
    standing7d: "STABLE",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Featured in UAE agency synthesis list for full-stack digital marketing.",
    recommendation: "Strengthen GCC client success proof points.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "Dubai",
    keyword: "seo company dubai",
    targetPage: "/services/dubai-seo/",
    market: "AE",
    device: "Desktop",
    organicPosition: 3.1,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/dubai-seo/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Organic position 3.1 with direct attribution snippet in Google AI summary.",
    recommendation: "Maintain localized GCC business schema.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "Dubai",
    keyword: "aeo agency dubai",
    targetPage: "/aeo-dubai/",
    market: "AE",
    device: "Desktop",
    organicPosition: 1.9,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/aeo-dubai/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Sole dedicated AEO agency cited in Dubai regional generative search.",
    recommendation: "Preserve high-relevance conversational search targeting.",
    rectificationWorkflow: "APPROVED",
  },
  {
    cluster: "Dubai",
    keyword: "generative ai video dubai",
    targetPage: "/services/ai-production-dubai-page/",
    market: "AE",
    device: "Desktop",
    organicPosition: 2.0,
    aiOverviewTriggered: true,
    dgsCited: true,
    dgsUrl: "https://www.dgeniussolutions.com/services/ai-production-dubai-page/",
    lastChecked: "2026-09-27",
    standing7d: "UP",
    standing15d: "UP",
    standing28d: "UP",
    issueDiagnosis: "Top generative video producer citation across UAE search surfaces.",
    recommendation: "Maintain strict frozen state on Dubai landing route.",
    rectificationWorkflow: "APPROVED",
  },
];
