export type AiOverviewCluster = "AI Video" | "SEO" | "AEO" | "GEO" | "LLM" | "Dubai";

export type AiOverviewStatus =
  | "AI_OVERVIEW_DGS_CITED"
  | "AI_OVERVIEW_DGS_NOT_CITED"
  | "AI_OVERVIEW_NOT_TRIGGERED"
  | "NOT_CHECKED"
  | "INSUFFICIENT_EVIDENCE";

export type MissedOpportunityDiagnostics = {
  wrongLandingPage: boolean;
  cannibalisation: boolean;
  indexability: "INDEXABLE" | "RESTRICTED";
  canonical: "ACCURATE" | "MISMATCH";
  snippetRestriction: boolean;
  intentMismatch: boolean;
  weakFirstPartyEvidence: boolean;
  missingCaseStudy: boolean;
  internalLinkingDeficit: boolean;
  entityClarity: "HIGH" | "MEDIUM" | "LOW";
  contentOverlap: boolean;
  schemaMismatch: boolean;
  rootCauseSummary: string;
  recommendedRectification: string;
};

export type AiOverviewKeywordItem = {
  keyword: string;
  cluster: AiOverviewCluster;
  targetPage: string;
  market: string;
  device: "Desktop" | "Mobile";
  checkedAt: string;
  searchUrl: string;
  aiOverviewTriggered: "YES" | "NO" | "NOT_CHECKED";
  dgsCited: "YES" | "NO" | "NOT_CHECKED";
  dgsCitedUrl: string;
  normalOrganicPosition?: number;
  evidenceSource: string;
  evidenceId: string;
  screenshotExists: boolean;
  observer: string;
  status: AiOverviewStatus;
  standing7d?: "UP" | "DOWN" | "STABLE" | "NEW";
  standing15d?: "UP" | "DOWN" | "STABLE" | "NEW";
  standing28d?: "UP" | "DOWN" | "STABLE" | "NEW";
  diagnostics?: MissedOpportunityDiagnostics;
};

export type OfficialGenerativeAiReport = {
  available: boolean;
  status: "MANUAL_EXPORT_REQUIRED" | "CONNECTED" | "NOT_CONFIGURED";
  lastSuccessfulSync: string | null;
  dataThroughDate: string | null;
  pagesWithImpressions: number;
  totalOfficialAiImpressions: number;
  supportedDimensions: string[];
  source: string;
  fetchedAt: string | null;
  rawEvidenceReference: string | null;
  officialDisclaimer: string;
};

export const OFFICIAL_GENERATIVE_AI_REPORT: OfficialGenerativeAiReport = {
  available: false,
  status: "MANUAL_EXPORT_REQUIRED",
  lastSuccessfulSync: null,
  dataThroughDate: null,
  pagesWithImpressions: 0,
  totalOfficialAiImpressions: 0,
  supportedDimensions: ["Page", "Country", "Date", "Device"],
  source: "Google Search Console - Generative AI Performance Report",
  fetchedAt: null,
  rawEvidenceReference: null,
  officialDisclaimer:
    "Official Google Search Console Generative AI Performance report is not ingested via automated API. No synthetic data is generated. Official data requires manual GSC export.",
};

export const AI_OVERVIEW_31_KEYWORDS: AiOverviewKeywordItem[] = [
  // Cluster 1: AI Video (8 Keywords)
  {
    keyword: "ai video production agency in mumbai",
    cluster: "AI Video",
    targetPage: "/services/ai-video-production-agency/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=ai+video+production+agency+in+mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.8,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "ai video production house in mumbai",
    cluster: "AI Video",
    targetPage: "/services/ai-video-production-agency/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=ai+video+production+house+in+mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 4.6,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "AI Avatar Videos in Mumbai",
    cluster: "AI Video",
    targetPage: "/services/ai-video-production-agency/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=AI+Avatar+Videos+in+Mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 2.1,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "AI Festival Videos in Mumbai",
    cluster: "AI Video",
    targetPage: "/services/ai-video-production-agency/",
    market: "IN",
    device: "Mobile",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=AI+Festival+Videos+in+Mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 6.2,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "AI TV commercials in Mumbai",
    cluster: "AI Video",
    targetPage: "/services/ai-video-production-agency/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=AI+TV+commercials+in+Mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 2.4,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "AI OTT video series in Mumbai",
    cluster: "AI Video",
    targetPage: "/services/ai-video-production-agency/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=AI+OTT+video+series+in+Mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.5,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "AI OTT video ads in Mumbai",
    cluster: "AI Video",
    targetPage: "/services/ai-video-production-agency/",
    market: "IN",
    device: "Mobile",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=AI+OTT+video+ads+in+Mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 4.1,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "ai commercial video production",
    cluster: "AI Video",
    targetPage: "/services/ai-video-production-agency/",
    market: "Global",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=ai+commercial+video+production",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 8.9,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },

  // Cluster 2: SEO (5 Keywords)
  {
    keyword: "seo services in mumbai",
    cluster: "SEO",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=seo+services+in+mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 3.2,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "best seo company mumbai",
    cluster: "SEO",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=best+seo+company+mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 4.8,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "digital marketing agency mumbai",
    cluster: "SEO",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "IN",
    device: "Mobile",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=digital+marketing+agency+mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 9.1,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "enterprise seo services",
    cluster: "SEO",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "Global / IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=enterprise+seo+services",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 5.7,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "technical seo audit services",
    cluster: "SEO",
    targetPage: "/services/seo-services-in-mumbai/",
    market: "Global / IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=technical+seo+audit+services",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 3.4,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },

  // Cluster 3: AEO (5 Keywords)
  {
    keyword: "aeo services in mumbai",
    cluster: "AEO",
    targetPage: "/services/aeo-services-in-mumbai/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=aeo+services+in+mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.2,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "answer engine optimization agency",
    cluster: "AEO",
    targetPage: "/services/aeo-services-in-mumbai/",
    market: "Global / IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=answer+engine+optimization+agency",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 2.1,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "what is answer engine optimization",
    cluster: "AEO",
    targetPage: "/blogs/what-is-llm-seo/",
    market: "Global",
    device: "Mobile",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=what+is+answer+engine+optimization",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 4.8,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "aeo vs seo services",
    cluster: "AEO",
    targetPage: "/blogs/geo-vs-seo-google-ai-search/",
    market: "Global",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=aeo+vs+seo+services",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 2.9,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "aeo pricing packages india",
    cluster: "AEO",
    targetPage: "/services/aeo-services-in-mumbai/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=aeo+pricing+packages+india&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 3.1,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },

  // Cluster 4: GEO (4 Keywords)
  {
    keyword: "geo services in mumbai",
    cluster: "GEO",
    targetPage: "/services/geo/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=geo+services+in+mumbai&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.1,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "generative engine optimization agency",
    cluster: "GEO",
    targetPage: "/services/geo/",
    market: "Global / IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=generative+engine+optimization+agency",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.8,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "geo optimization for brands",
    cluster: "GEO",
    targetPage: "/services/geo/",
    market: "Global",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=geo+optimization+for+brands",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 2.7,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "geo vs aeo",
    cluster: "GEO",
    targetPage: "/blogs/geo-vs-seo-google-ai-search/",
    market: "Global",
    device: "Mobile",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=geo+vs+aeo",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 3.5,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },

  // Cluster 5: LLM (5 Keywords)
  {
    keyword: "llm seo services",
    cluster: "LLM",
    targetPage: "/services/llm-seo-service/",
    market: "Global / IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=llm+seo+services",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.4,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "llm seo agency india",
    cluster: "LLM",
    targetPage: "/services/llm-seo-service/",
    market: "IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=llm+seo+agency+india&gl=in",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.2,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "large language model search optimization",
    cluster: "LLM",
    targetPage: "/services/llm-seo-service/",
    market: "Global",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=large+language+model+search+optimization",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 2.3,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "chatgpt brand visibility optimization",
    cluster: "LLM",
    targetPage: "/blogs/chatgpt-brand-visibility/",
    market: "Global / IN",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=chatgpt+brand+visibility+optimization",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 3.8,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "perplexity optimization services",
    cluster: "LLM",
    targetPage: "/services/llm-seo-service/",
    market: "Global",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=perplexity+optimization+services",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 2.0,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },

  // Cluster 6: Dubai (4 Keywords)
  {
    keyword: "ai video production agency in dubai",
    cluster: "Dubai",
    targetPage: "/services/ai-production-dubai-page/",
    market: "AE",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=ai+video+production+agency+in+dubai&gl=ae",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.6,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "dubai ai production company",
    cluster: "Dubai",
    targetPage: "/services/ai-production-dubai-page/",
    market: "AE",
    device: "Mobile",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=dubai+ai+production+company&gl=ae",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 2.3,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "digital marketing agency dubai",
    cluster: "Dubai",
    targetPage: "/services/dubai-seo/",
    market: "AE",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=digital+marketing+agency+dubai&gl=ae",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 5.4,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
  {
    keyword: "aeo agency dubai",
    cluster: "Dubai",
    targetPage: "/aeo-dubai/",
    market: "AE",
    device: "Desktop",
    checkedAt: "2026-10-02",
    searchUrl: "https://www.google.com/search?q=aeo+agency+dubai&gl=ae",
    aiOverviewTriggered: "NOT_CHECKED",
    dgsCited: "NOT_CHECKED",
    dgsCitedUrl: "None",
    normalOrganicPosition: 1.9,
    evidenceSource: "Awaiting verified SERP observation / manual verification",
    evidenceId: "AWAITING_VERIFIED_SERP_CAPTURE",
    screenshotExists: false,
    observer: "None",
    status: "NOT_CHECKED",
    standing7d: "STABLE",
    standing15d: "STABLE",
    standing28d: "STABLE",
  },
];
