#!/usr/bin/env node
/**
 * Generate Next.js mirror route files from data/wordpress/manifest.json
 * Usage: node scripts/generate-routes.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const MANIFEST = path.join(ROOT, "data", "wordpress", "manifest.json");
const MIRROR_APP = path.join(ROOT, "app", "(mirror)");

function routeSegments(routePath) {
  const trimmed = routePath.replace(/^\/|\/$/g, "");
  if (!trimmed) return [];
  return trimmed.split("/");
}

function pageFilePath(segments) {
  if (segments.length === 0) {
    return path.join(MIRROR_APP, "page.jsx");
  }
  return path.join(MIRROR_APP, ...segments, "page.jsx");
}

function pageSource(entry) {
  const contentKey = entry.contentKey;
  return `/* AUTO-GENERATED by scripts/generate-routes.mjs — do not edit */
import WpMirrorPage, { buildMetadata } from "@/components/mirror/WpMirrorPage";
import content from "@/data/wordpress/content/${contentKey}.json";

export const metadata = buildMetadata(content);

export default function Page() {
  return <WpMirrorPage content={content} />;
}
`;
}

function ensureDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function cleanGenerated(dir) {
  if (!fs.existsSync(dir)) return;
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    if (fs.statSync(p).isDirectory()) cleanGenerated(p);
    else if (name === "page.jsx") fs.unlinkSync(p);
  }
}

function main() {
  if (!fs.existsSync(MANIFEST)) {
    console.error("Run npm run sync:wp first");
    process.exit(1);
  }
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
  cleanGenerated(MIRROR_APP);

  const indexTs = [];

  for (const entry of manifest.routes) {
    const segments = routeSegments(entry.path);
    const file = pageFilePath(segments);
    ensureDir(file);
    fs.writeFileSync(file, pageSource(entry));
    indexTs.push(
      `  "${entry.path}": () => import("@/data/wordpress/content/${entry.contentKey}.json"),`
    );
    console.log("generated", entry.path, "→", path.relative(ROOT, file));
  }

  const loaderPath = path.join(ROOT, "lib", "wordpress", "content-loader.ts");
  fs.mkdirSync(path.dirname(loaderPath), { recursive: true });
  fs.writeFileSync(
    loaderPath,
    `/* AUTO-GENERATED */
export const CONTENT_LOADERS: Record<string, () => Promise<{ default: unknown }>> = {
${indexTs.join("\n")}
};
`
  );

  console.log(`\nGenerated ${manifest.routes.length} routes.`);
}

main();
