/* AUTO-GENERATED by scripts/generate-routes.mjs — do not edit */
import WpMirrorPage, { buildMetadata } from "@/components/mirror/WpMirrorPage";
import content from "@/data/wordpress/content/post-social-media-conversion-why-your-followers-are-not-becoming-customers.json";

export const metadata = buildMetadata(content);

export default function Page() {
  return <WpMirrorPage content={content} />;
}
